annotations:
  licenses: Apache-2.0
apiVersion: v2
appVersion: v0.41.4
dependencies:
  - name: common
    repository: file://../common
    version: 2.x.x
description: Template rendering, notifier, and supervisor for @hashicorp Consul and Vault data.
home: https://github.com/fsdrw08/helm-charts
keywords:
  - consul
  - vault
  - nomad
  - template
maintainers:
  - name: Windom WU
    url: https://github.com/fsdrw08/helm-charts
name: consul-template
sources:
  - https://github.com/fsdrw08/helm-charts/tree/main/charts/consul-template
  - https://github.com/hashicorp/consul-template
  - https://github.com/hashicorp/consul-template/blob/v0.41.4/Dockerfile
version: 0.1.0
