annotations:
  # CHOOSE_ONE_FROM_CHART_CATEGORIES_FILE
  # https://github.com/bitnami/charts/blob/main/CHART_CATEGORIES
  category: Infrastructure
  licenses: Apache-2.0
apiVersion: v2
appVersion: 5.0.2
dependencies:
  - name: common
    repository: file://../common
    version: 2.x.x
description: PowerDNS auth server helm chart for podman kube play
home: https://github.com/fsdrw08/helm-charts
icon: https://github.com/PowerDNS/pdns/blob/90dfa3d8655a0e654778655b776c5ee4e937c0f9/docs/common/powerdns-logo-500px.png
keywords:
  - powerdns
  - pdns
  - dns
  - podman kube play
maintainers:
  - name: Windom WU
    url: https://github.com/fsdrw08/helm-charts
name: powerdns
sources:
  - https://github.com/fsdrw08/helm-charts/tree/main/charts/pdns-auth
  - https://github.com/PowerDNS/pdns/tree/master
version: 0.1.0
