annotations:
  licenses: Apache-2.0
apiVersion: v2
appVersion: v4.6.1
dependencies:
  - name: common
    repository: file://../common
    version: 2.x.x
description: ZITADEL Hosted Login Version 2
home: https://github.com/fsdrw08/helm-charts
icon: https://zitadel.com/zitadel-logo-dark.svg
keywords:
  - oidc
  - saml
  - podman kube play
maintainers:
  - name: Windom WU
    url: https://github.com/fsdrw08/helm-charts/tree/main/charts/zitadel-frontend
name: zitadel-frontend
sources:
  - https://github.com/zitadel/zitadel/blob/v4.6.1/apps/login/Dockerfile
  - https://github.com/zitadel/zitadel/pkgs/container/zitadel-login
  - ...
version: 0.1.0
