annotations:
  # CHOOSE_ONE_FROM_CHART_CATEGORIES_FILE
  # https://github.com/bitnami/charts/blob/main/CHART_CATEGORIES
  category: Analytics
  images: |
    - name: prometheus
      image: quay.io/prometheus/prometheus:v3.7.2
  licenses: Apache-2.0
apiVersion: v2
appVersion: v3.7.2
dependencies:
  - name: common
    repository: file://../common
    version: 2.x.x
description:
  Prometheus is an open source monitoring and alerting system. It enables
  sysadmins to monitor their infrastructures by collecting metrics from configured
  targets at given intervals.
home: https://github.com/prometheus/prometheus
icon: https://dyltqmyl993wv.cloudfront.net/assets/stacks/prometheus/img/prometheus-stack-220x234.png
keywords:
  - prometheus
  - monitoring
  - podman kube play
maintainers:
  - name: Windom WU
    url: https://github.com/fsdrw08/helm-charts
name: prometheus
sources:
  - https://github.com/fsdrw08/helm-charts/tree/main/charts/prometheus
  - https://github.com/prometheus/prometheus
  - https://github.com/prometheus-community/helm-charts
  - https://github.com/prometheus/prometheus/blob/v3.7.2/Dockerfile
  - ...
version: 0.1.0
