annotations:
  # CHOOSE_ONE_FROM_CHART_CATEGORIES_FILE
  # https://github.com/bitnami/charts/blob/main/CHART_CATEGORIES
  category: DeveloperTools
  licenses: Apache-2.0
apiVersion: v2
appVersion: 26.4.2.7
dependencies:
  - name: common
    repository: file://../common
    version: 2.x.x
description: Keycloak is a high performance Java-based identity and access management solution. It lets developers add an authentication layer to their applications with minimum effort.
home: https://github.com/fsdrw08/helm-charts
icon: https://bitnami.com/assets/stacks/keycloak/img/keycloak-stack-220x234.png
keywords:
  - keycloak
  - access-management
  - ...
maintainers:
  - name: Windom WU
    url: https://github.com/fsdrw08/helm-charts
name: keycloak
sources:
  - https://github.com/fsdrw08/helm-charts/tree/main/charts/keycloak
  - https://github.com/keycloak/keycloak
  - ...
version: 0.1.0
