annotations:
  # CHOOSE_ONE_FROM_CHART_CATEGORIES_FILE
  # https://github.com/bitnami/charts/blob/main/CHART_CATEGORIES
  category: Infrastructure
  licenses: Apache-2.0
apiVersion: v2
appVersion: v3.6.4
dependencies:
  - name: common
    repository: file://../common
    version: 2.x.x
description:
  Grafana Loki is a horizontally scalable, highly available, and multi-tenant
  log aggregation system. It provides real-time long tailing and full persistence
  to object storage.
home: https://github.com/fsdrw08/helm-charts
icon: https://bitnami.com/assets/stacks/%%IMAGE_NAME%%/img/%%IMAGE_NAME%%-stack-220x234.png
keywords:
  - grafana
  - tracing
  - metrics
  - infrastructure
  - podman kube play
maintainers:
  - name: Windom WU
    url: https://github.com/fsdrw08/helm-charts
name: loki
sources:
  - https://github.com/fsdrw08/helm-charts/tree/main/charts/loki
  - https://github.com/grafana/loki
  - https://github.com/grafana/loki/blob/v3.6.4/cmd/loki/Dockerfile
version: 0.1.0
