annotations:
  # CHOOSE_ONE_FROM_CHART_CATEGORIES_FILE
  # https://github.com/bitnami/charts/blob/main/CHART_CATEGORIES
  category: Infrastructure
  licenses: Apache-2.0
apiVersion: v2
# https://github.com/coredns/helm/blob/master/charts/coredns/Chart.yaml
appVersion: 1.13.2
dependencies:
  - name: common
    repository: file://../common
    version: 2.x.x
description: CoreDNS is a DNS server that chains plugins
home: https://github.com/fsdrw08/helm-charts
icon: https://coredns.io/images/CoreDNS_Colour_Horizontal.png
keywords:
  - podman kube play
  - coredns
  - dns
maintainers:
  - name: Windom WU
    url: https://github.com/fsdrw08/helm-charts
name: coredns
sources:
  - https://github.com/fsdrw08/helm-charts/tree/main/charts/coredns
version: 0.1.0
