annotations:
  # CHOOSE_ONE_FROM_CHART_CATEGORIES_FILE
  # https://github.com/bitnami/charts/blob/main/CHART_CATEGORIES
  category: Database
  licenses: Apache-2.0
apiVersion: v2
appVersion: 8.4.0
dependencies:
  - name: common
    repository: file://../common
    version: 2.x.x
description:
  Redis(R) is an open source, advanced key-value store. It is often referred
  to as a data structure server since keys can contain strings, hashes, lists, sets
  and sorted sets.
home: https://github.com/fsdrw08/helm-charts
icon: https://dyltqmyl993wv.cloudfront.net/assets/stacks/redis/img/redis-stack-220x234.png
keywords:
  - redis
  - keyvalue
  - database
maintainers:
  - name: Windom WU
    url: https://github.com/fsdrw08/helm-charts
name: redis
sources:
  - https://github.com/fsdrw08/helm-charts/tree/main/charts/redis
  - https://github.com/redis/docker-library-redis/tree/release/8.2
  - ...
version: 0.1.0
